name: Commit gha config ymls
on:
    workflow_dispatch:
        inputs:
            repo_name:
                description: |
                    Specify name of the repository to commit the file to.
                required: true
permissions:
  contents: write

jobs:
  copy_action_file:
      runs-on: ubuntu-latest
      steps:
        - name: Push config files to ${{ github.event.inputs.repo_name }}
          uses: nkoppel/push-files-to-another-repository@v1.1.3
          env:
            API_TOKEN_GITHUB: ${{ secrets.REPO_ADMIN_TOKEN_MH }}
          with:
            source-files: .github/release-drafter.yml
            destination-username: Ordermentum
            destination-repository: ${{ github.event.inputs.repo_name }}
            destination-branch: develop
            destination-directory: .github
            commit-email: ${{ github.actor }}@users.noreply.github.com
            commit-username: ${{ github.actor }}
            commit-message: "Add gha config files"
