name: Copy base actions to required repos

on:
    push:
        branches: [ main ]
    workflow_dispatch:
        inputs:
            repo_name:
                description: |
                    Specify name of the repository where workflows should be pushed manually.
                    If you do not specify exact repository name, the workflow will try to replicate all missing changes to all repositories.
                required: false

jobs:
    replicate_changes:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: derberg/manage-files-in-multiple-repositories@v2
              with:
                github_token: ${{ secrets.REPO_ADMIN_TOKEN_MH }}
                repos_to_ignore: 'magikarp,alakazam,togepi,snorlax,machop,infernape,java-sdk'
                patterns_to_include: '.github/release-drafter.yml,.github/workflows'
                patterns_to_ignore: '.github/workflows/copy-actions.yml'
                bot_branch_name: 'ci/update-github-actions-workflows'


            