name: Copy base actions to required repos

on:
    workflow_dispatch:
        inputs:
            repo_name:
                description: |
                    Specify name of the repository where workflows should be pushed manually.
                    If you do not specify exact repository name, the workflow will try to replicate all missing changes to all repositories.
                required: true

jobs:
    replicate_changes:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: derberg/manage-files-in-multiple-repositories@v2
              with:
                github_token: ${{ secrets.REPO_ADMIN_TOKEN_MH }}
                repos_to_ignore: 'public-supplier-pages-poc,workstation-checker,sugendran-test,UserPersonaSurvey,node-job-prisma-template,togepi-playground,node-service-template-hapi,cart-javascript-sdk,gists,invoice-email,devopsthings,centurion-ios,spreedly,starter-pack,Field-App-iOS,asclepius,lion-sap-curl-scripts,jvm-packages,blondie,promotions,testjvmpackage,helm-charts,om-pgbouncer,promisepay-sdk,redux-test,sequelize,osx,lambda-workers,lambda-worker-base,appium-ios-python,sundial-neon,redheads,appium-android-python,appium-android-dotnet,appium-android-java,unleashed-jvm,appium-android-js,dynamics,ordermentum-bot,code-kata,data-science,apitesting,docker-pgbouncer,om-weather-app,kristest,looker,http-server,alexa,aws-rotate-key,ant-design,Kotlin-Shared,charts,PPBadgeView,integration-performance-tester,dev-docker-scripts,ktmono,TTTTT,orchestration,api-gateway,async-iterator-pg-cursor,psandqs,klasifikat-r,ordermentumbot,postman,reporting,api-test,kotlin-base-stack,certificates,price-index,asclepius-standard,template,qdc,aba,flags,yup-uuid,axios-opentracing,sequelize-batches,eslint-config-ordermentum,engineering-site,Automation,slider,greenfield,cli,oaknuggins,ui-components-elements,ui-styles-icons,memory-format,ui-styles-global,ipi,react-select-multi,luvdisc-client,null-logger,payments-javascript-sdk,myob-exo-javascript-sdk,myob-javascript-sdk,javascript-sdk,signup-ui,react-clickout,notifications-widget,xero-taxcode-taxonomy,mixpanel-remixed,widget,pagination-helper,node-oauth,barricade,docs,rrule,integration-tests,login,infrastructure,magikarp,togepi,alakazam,infernape,java-sdk,testrepo123,completion,api-gateway-v2,asap-proxy,auth-driver,cache-machine,slingshot,prowl,machop,retry-machine,psyduck,api-docs,snorlax,steveo-trace-provider-newrelic,changelog,node-job-template,node-service-template,elastalert,ordermentum-notifications,newrelic-steveo,projections,dochub,sundial,playground-eks-cluster,datadef,bushfires,crossover,autobuilder,ledger,authentication,Kotlin-Service-Seed,cheatsheet,dashiell-robert-parr,webhook-load-testing,index-graph'
                patterns_to_include: '.github/release-drafter.yml,.github/workflows'
                patterns_to_ignore: '.github/workflows/copy-base-actions.yml,.github/workflows/copy-mobile-actions.yml,.github/workflows/NewReleasePr.yml,.github/workflows/TagAndRelease.yml'
                bot_branch_name: 'ci/update-github-actions-workflows'


            
