name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - develop
  # pull_request event is required only for autolabeler
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]
    # branches:
    #   - develop
  pull_request_target:
    types: [opened, reopened, synchronize]
    # branches:
    #   - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Set version
        id: version
        run: |
          RELEASE_VERSION=v$(TZ='Australia/Sydney' date +'%Y.%m.%d-%H%M')
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          cat $GITHUB_ENV
      - name: Create draft
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          version: ${{ env.RELEASE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
