name: Pull Request Stats

on:
  workflow_dispatch:
        inputs:
            period:
                description: |
                    Specify the time period to check against.
                required: true
                default: "7"

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          token: ${{ secrets.REPO_ADMIN_TOKEN_MH }}
          organization: 'ordermentum'
          period: ${{ github.event.inputs.period }}
          sortBy: 'REVIEWS'
          charts: true
          disableLinks: true
          # webhook: 'https://hooks.zapier.com/hooks/catch/13747462/2b4lp8c/'
